### ISSUE TITLE
Исследование аналитических БД

### ISSUE THREAD

**Issue by AlexBlackNn** [KarinaRin/ugc_sprint_1_ours#10]

**Comment by AlexBlackNn** [comment]
1. [тут](https://github.com/KarinaRin/ugc_sprint_1_ours/blame/b45bb753c60e57c6169d7810b0244201a461fd15/storage_research/docker-compose.yml#L18) версия вертики 4 летней давности. Кажется, лучше использовать https://hub.docker.com/r/vertica/vertica-ce отсюда

2. Идеологически из readme
Загрузка или генерация первоначальных данных
Вставка данных производится пачками по 10 тыс.записей.
В результате хранилища будут заполнены **10 млн.** сгенерированных данных. 
Предполагается (_в целях задачи)_, 1 млн. пользователей и 10000 фильмов.

 [Тут](https://clickhouse.com/docs/en/cloud/bestpractices/bulk-inserts ) рекомендуется делать вставки с 10 000 - до 100 000 строк. Сейчас исследование проведено для НЕ рекомендуемых размеров батчей. Запись лучше делать с задержкой в сек (Regardless of the size of your inserts, we recommend keeping the number of insert queries around one insert query per second.) и можно попробовать и без задержки для сравнения. Ожидаю, исходя из документации наивысшую скорость записи при размере батча между 10 000 - 100 000 строк.

 3.  Из readme.
 Для запуска тестов вставки необходимо в папке test_results запустить скрипты (очередность важна!): сначала insert_test_clickhouse.py, а затем insert_test_vertica.py 
 Лучше чтобы запуск одного теста не влиял на запуск другого теста. Ведь, если я захочу отредактировать  insert_test_vertica и запустить его отдельно, придется запускать и ждать завершения теста с кликом.

4. Следует отметить, что несмотря на то, что данные приводятся усредненные после выборки из 10 повторений по каждому типу пакета данных, при повторении теста разброс данных внутри каждого хранилища достигал порой 50%. 
Кажется, разброс большой от опыта к опыту. Неплохо было бы построить [доверительные интервалы](https://ru.wikipedia.org/wiki/%D0%94%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D0%B0%D0%BB_%D0%B4%D0%BB%D1%8F_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9_%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%BA%D0%B8#:~:text=%D0%94%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D0%B0%D0%BB%20%D0%B4%D0%BB%D1%8F%20%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F%20%E2%80%94%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B2%D0%B0%D0%BB%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9%20%D1%81%20%D0%B8%D0%B7%D0%B2%D0%B5%D1%81%D1%82%D0%BD%D0%BE%D0%B9%20%D0%B2%D0%B5%D1%80%D0%BE%D1%8F%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C%D1%8E,%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D1%82%20%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5%20%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9%20%D1%81%D0%BE%D0%B2%D0%BE%D0%BA%D1%83%D0%BF%D0%BD%D0%BE%D1%81%D1%82%D0%B8.) 

5.  [Тут](https://github.com/KarinaRin/ugc_sprint_1_ours/blame/15ace50af6c8852a1fe216bfa9c3f50634a813c8/storage_research/clickhouse.py#L27) не понял... 
Мы ловим ошибку и ее заново вызываем? 
Аналогично  для Вертики.

6 [Тут](https://github.com/KarinaRin/ugc_sprint_1_ours/blob/15ace50af6c8852a1fe216bfa9c3f50634a813c8/storage_research/clickhouse.py#L32) замер скорости записи идет с учетом времени генерации данных (хоть и не значительного, для 10000 примерно 0.01 на генерацию одного батча, для 100000  0.11 на моем ПК.  )

7 [Тут](https://github.com/KarinaRin/ugc_sprint_1_ours/blob/15ace50af6c8852a1fe216bfa9c3f50634a813c8/storage_research/test_results/select_test_vertica.py#L1)
 """"Измерение скорости вставки данных в заполненное хранилище"""" Судя по sql запросам, название не соответствует действительности.
 Аналогичных файлов с именем "select_..."

**Comment by OlegPletnev** [comment]
п.1 -  версию обновил.
п.2 -  чанки до 1 млн. добавлены
п.3 -  пусть с гемором, но задача решена: теперь не важно когда-какой скрипт теста запускать
п.4 -  обошлись без доверительных интервалов
п.5 -  убрал ловлю ошибки - все равно нужен лишь трэйсбек
п.6 -  в указанном месте расчет скорости не производится - эта функция для инициализации 10 млн записей
п.7 -  Доки поправил
п.8 -  вынес sql-запросы в отдельный файл
