### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [KarinaRin/ugc_sprint_1_ours#14]
Просто к сведению про ETL: использование `Engine = Kafka` упрощает работу, но лишает нас возможности промежуточного преобразования данных, как это было бы возможно в ETL 😀

Исследование отличное и прекрасное оформление результатов 👍

Вопросы только к API:

1. Вот [тут](https://github.com/KarinaRin/ugc_sprint_1_ours/blob/16f60cecb3ed562a86177c6e5b113f8adf071ae8/src/api/v1/view.py#L26) асинхронная функция, а [вот тут](https://github.com/KarinaRin/ugc_sprint_1_ours/blob/16f60cecb3ed562a86177c6e5b113f8adf071ae8/src/api/v1/view.py#L32) нет ничего асинхронного (и во втором эндпоинте тоже). Это плохо, так как заблокируется цикл событий и вся асинхронность превратится в тыкву. Выходов как всегда несколько:
      - использовать асинхронную библиотеку https://aiokafka.readthedocs.io/en/stable/#aiokafkaproducer
      - сделать все это синхронным, все эти две функции: эндпоинт и в сервисе. И тогда FastAPI их отправит в тредпул и сделает "асинхронными" https://fastapi.tiangolo.com/async/ (но это не лучшее решение, так как со временем в эндпоинте может появиться что-то асинхронное и придется все переделывать по первому варианту)
2. В продолжение п.1, обязательно нужно учесть это замечание и при работе с Redis. У вас там тоже все очень даже синхронно. Используйте https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html
3. Необходимо указывать [аннотацию для передаваемых аргументов](https://github.com/KarinaRin/ugc_sprint_1_ours/blob/16f60cecb3ed562a86177c6e5b113f8adf071ae8/src/db/kafka.py#L11) и возвращаемых значений. Так уменьшается вероятность ошибки и повышается читаемость кода.

**Comment by KarinaRin** [comment]
Замечания исправлены
